In [6]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sbn
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

In [5]:
df=pd.read_csv("./hearing_test.csv")
X=df.drop("test_result",axis=1)
Y=df["test_result"]
df.head()

age  physical_score  test_result
0  33.0            40.7            1
1  50.0            37.2            1
2  52.0            24.7            0
3  56.0            31.0            0
4  35.0            42.9            1

In [8]:
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.10, random_state=42)
standard_model=StandardScaler()
X_train=standard_model.fit_transform(X_train)
X_test=standard_model.fit_transform(X_test)

In [9]:
model=LogisticRegression()
model.fit(X_train,y_train)

LogisticRegression()

In [12]:
model.coef_

array([[-0.91841476,  3.52854047]])

In [10]:
prediction=model.predict(X_test)

In [11]:
prediction

array([1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0,
       0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0,
       1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1,
       1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1,
       1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0,
       1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1,
       1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0,

In [14]:
model.predict_proba(X_test)

array([[4.42846732e-02, 9.55715327e-01],
       [9.83009644e-01, 1.69903559e-02],
       [3.76393359e-02, 9.62360664e-01],
       [4.22133501e-03, 9.95778665e-01],
       [9.35237032e-01, 6.47629683e-02],
       [7.91181713e-01, 2.08818287e-01],
       [9.98675006e-01, 1.32499412e-03],
       [1.74156499e-01, 8.25843501e-01],
       [2.14223495e-01, 7.85776505e-01],
       [9.97536203e-01, 2.46379685e-03],
       [4.41729190e-01, 5.58270810e-01],
       [9.77180739e-01, 2.28192613e-02],
       [2.97297029e-02, 9.70270297e-01],
       [7.67998478e-02, 9.23200152e-01],
       [1.96629889e-01, 8.03370111e-01],
       [9.99463941e-01, 5.36059294e-04],
       [1.10876218e-01, 8.89123782e-01],
       [9.45792707e-01, 5.42072931e-02],
       [3.79246996e-02, 9.62075300e-01],
       [6.94743683e-01, 3.05256317e-01],
       [6.57868238e-01, 3.42131762e-01],
       [9.77975414e-01, 2.20245864e-02],
       [9.80427724e-01, 1.95722763e-02],
       [2.78741365e-01, 7.21258635e-01],
       [5.952008