In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler,PolynomialFeatures
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error,mean_squared_error
from sklearn.linear_model import LassoCV

In [2]:
df=pd.read_csv("./Advertising.csv")
X=df.drop("sales",axis=1)
Y=df["sales"]
df.head()




TV  radio  newspaper  sales
0  230.1   37.8       69.2   22.1
1   44.5   39.3       45.1   10.4
2   17.2   45.9       69.3    9.3
3  151.5   41.3       58.5   18.5
4  180.8   10.8       58.4   12.9

In [3]:
poly_convertor=PolynomialFeatures(degree=3,)
poly_features=poly_convertor.fit_transform(X)
poly_features

array([[1.00000000e+00, 2.30100000e+02, 3.78000000e+01, ...,
        9.88757280e+04, 1.81010592e+05, 3.31373888e+05],
       [1.00000000e+00, 4.45000000e+01, 3.93000000e+01, ...,
        6.96564990e+04, 7.99365930e+04, 9.17338510e+04],
       [1.00000000e+00, 1.72000000e+01, 4.59000000e+01, ...,
        1.46001933e+05, 2.20434291e+05, 3.32812557e+05],
       ...,
       [1.00000000e+00, 1.77000000e+02, 9.30000000e+00, ...,
        5.53536000e+02, 3.80928000e+02, 2.62144000e+02],
       [1.00000000e+00, 2.83600000e+02, 4.20000000e+01, ...,
        1.16776800e+05, 1.84062480e+05, 2.90117528e+05],
       [1.00000000e+00, 2.32100000e+02, 8.60000000e+00, ...,
        6.43452000e+02, 6.50934000e+02, 6.58503000e+02]])

In [4]:
X_train, X_test, y_train, y_test = train_test_split(poly_features, Y, test_size=0.3, random_state=42)
standard_coonvertor=StandardScaler()
standard_coonvertor.fit(X_train)
X_train=standard_coonvertor.transform(X_train)
X_test=standard_coonvertor.transform(X_test)

In [5]:
lasso_model=LassoCV(eps=0.001,n_alphas=100)
lasso_model.fit(X_train,y_train)

/Users/user/opt/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_coordinate_descent.py:530: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 0.7572096436807811, tolerance: 0.3673738857142857
  model = cd_fast.enet_coordinate_descent(


LassoCV()

In [6]:
lasso_model=LassoCV(eps=0.1,n_alphas=100)
lasso_model.fit(X_train,y_train)

LassoCV(eps=0.1)

In [7]:
lasso_model.coef_

array([0.        , 0.97675148, 0.        , 0.        , 0.        ,
       3.8148913 , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ])

In [8]:
lasso_model.alpha_

0.4924531806474871

In [9]:
lasso_prediction=lasso_model.predict(X_test)

In [10]:
MAE=mean_absolute_error(y_test,lasso_prediction)
MAE

0.6811456342837983

In [11]:
MSRE=np.sqrt(mean_squared_error(y_test,lasso_prediction))
MSRE

1.0349127365478727

In [12]:
#more the alpha is more the number of coef will become zero

In [13]:
lasso_model=LassoCV(eps=0.001,n_alphas=100,max_iter=10000000)
lasso_model.fit(X_train,y_train)

LassoCV(max_iter=10000000)

In [14]:
lasso_model.coef_

array([ 0.        ,  5.15048089,  0.4274257 ,  0.29684446, -4.53337994,
        3.38937185, -0.4288993 ,  0.        ,  0.        ,  0.        ,
        1.17891049, -0.        ,  0.        ,  0.16706037, -0.        ,
        0.        ,  0.        ,  0.11083672,  0.        ,  0.06155549])

In [15]:
lasso_prediction=lasso_model.predict(X_test)

In [16]:
MAE=mean_absolute_error(y_test,lasso_prediction)
MAE

0.5123045552899829

In [17]:
MSRE=np.sqrt(mean_squared_error(y_test,lasso_prediction))
MSRE

0.6308043049172882