In [5]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler,PolynomialFeatures
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error,mean_squared_error
from sklearn.linear_model import ElasticNetCV

In [2]:
df=pd.read_csv("./Advertising.csv")
X=df.drop("sales",axis=1)
Y=df["sales"]
df.head()





TV  radio  newspaper  sales
0  230.1   37.8       69.2   22.1
1   44.5   39.3       45.1   10.4
2   17.2   45.9       69.3    9.3
3  151.5   41.3       58.5   18.5
4  180.8   10.8       58.4   12.9

In [3]:
poly_convertor=PolynomialFeatures(degree=3,)
poly_features=poly_convertor.fit_transform(X)
poly_features

array([[1.00000000e+00, 2.30100000e+02, 3.78000000e+01, ...,
        9.88757280e+04, 1.81010592e+05, 3.31373888e+05],
       [1.00000000e+00, 4.45000000e+01, 3.93000000e+01, ...,
        6.96564990e+04, 7.99365930e+04, 9.17338510e+04],
       [1.00000000e+00, 1.72000000e+01, 4.59000000e+01, ...,
        1.46001933e+05, 2.20434291e+05, 3.32812557e+05],
       ...,
       [1.00000000e+00, 1.77000000e+02, 9.30000000e+00, ...,
        5.53536000e+02, 3.80928000e+02, 2.62144000e+02],
       [1.00000000e+00, 2.83600000e+02, 4.20000000e+01, ...,
        1.16776800e+05, 1.84062480e+05, 2.90117528e+05],
       [1.00000000e+00, 2.32100000e+02, 8.60000000e+00, ...,
        6.43452000e+02, 6.50934000e+02, 6.58503000e+02]])

In [4]:
X_train, X_test, y_train, y_test = train_test_split(poly_features, Y, test_size=0.3, random_state=42)
standard_coonvertor=StandardScaler()
standard_coonvertor.fit(X_train)
X_train=standard_coonvertor.transform(X_train)
X_test=standard_coonvertor.transform(X_test)

In [9]:
# l1_ratio => l1/ l2 , if 1 then l1 100%
elastic_model=ElasticNetCV(eps=0.1,n_alphas=100,l1_ratio=[.1, .5, .7,.9, .95, .99, 1])
elastic_model.fit(X_train,y_train)

ElasticNetCV(eps=0.1, l1_ratio=[0.1, 0.5, 0.7, 0.9, 0.95, 0.99, 1])

In [10]:
elastic_model.coef_

array([0.        , 0.97675148, 0.        , 0.        , 0.        ,
       3.8148913 , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ])

In [11]:
elastic_model.alpha_

0.4924531806474871

In [12]:
elastic_model.alphas_

array([[49.24531806, 48.1131661 , 47.00704236, 45.92634845, 44.87049973,
        43.83892503, 42.83106627, 41.84637823, 40.88432821, 39.94439575,
        39.02607239, 38.12886132, 37.25227717, 36.39584573, 35.55910368,
        34.74159837, 33.94288754, 33.1625391 , 32.40013091, 31.65525052,
        30.92749496, 30.21647053, 29.52179258, 28.84308531, 28.17998155,
        27.53212257, 26.89915789, 26.28074511, 25.67654965, 25.08624468,
        24.50951084, 23.94603614, 23.39551575, 22.85765184, 22.33215345,
        21.81873629, 21.31712261, 20.82704105, 20.34822649, 19.88041989,
        19.42336819, 18.97682413, 18.54054613, 18.11429818, 17.69784969,
        17.29097537, 16.89345511, 16.50507386, 16.1256215 , 15.75489278,
        15.39268712, 15.03880859, 14.69306573, 14.35527153, 14.02524322,
        13.70280228, 13.38777427, 13.07998877, 12.77927927, 12.48548309,
        12.1984413 , 11.91799862, 11.64400332, 11.37630719, 11.1147654 ,
        10.85923647, 10.60958216, 10.36566741, 10.1