In [1]:
import numpy as np


In [2]:
ar=["Neeraj","Singh","Negi"]

In [3]:
nparray=np.array(ar)

In [4]:
nparray

array(['Neeraj', 'Singh', 'Negi'], dtype='<U6')

In [5]:
nparray.dtype

dtype('<U6')

In [6]:
nparray.shape

(3,)

In [7]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [8]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [9]:
identity=np.identity(4)

In [10]:
identity.dtype

dtype('float64')

In [11]:
identity[0][3]=2

In [12]:
transposee=identity.transpose()

In [13]:
transposee

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [2., 0., 0., 1.]])

In [14]:
a=list(np.arange(20))

In [15]:
a

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]

In [16]:
a=list(np.arange(20,40))
a

[20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39]

In [17]:
a=list(np.arange(20,40,5))
a

[20, 25, 30, 35]

In [18]:
a=np.zeros(10)
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [19]:
b=np.ones(5)
b

array([1., 1., 1., 1., 1.])

In [20]:
line=np.linspace(1,5,6)
line

array([1. , 1.8, 2.6, 3.4, 4.2, 5. ])

In [21]:
line=np.linspace(0,10,10)
line

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [22]:
random_=np.random.rand(10,10)
random_

array([[0.75556267, 0.1907103 , 0.43808693, 0.05335904, 0.61866843,
        0.58789223, 0.23339547, 0.34376165, 0.51726499, 0.93296654],
       [0.42631955, 0.10518598, 0.12288931, 0.67724925, 0.77295599,
        0.96681765, 0.60291706, 0.35826308, 0.62799459, 0.69045326],
       [0.17937689, 0.38290476, 0.23729761, 0.96035465, 0.76108169,
        0.14127529, 0.71938605, 0.44130088, 0.67843345, 0.58901257],
       [0.84388691, 0.62175678, 0.87229563, 0.36820327, 0.95782322,
        0.46598431, 0.73719233, 0.03645288, 0.88706463, 0.23007075],
       [0.11184493, 0.89023704, 0.73575505, 0.51941771, 0.3866713 ,
        0.22726415, 0.04219535, 0.7970341 , 0.00980405, 0.57089373],
       [0.99597014, 0.16479945, 0.74452389, 0.80418133, 0.27129054,
        0.6130016 , 0.24018446, 0.27653573, 0.96271189, 0.61780473],
       [0.8374319 , 0.56896989, 0.44673548, 0.34984592, 0.52150436,
        0.78006785, 0.77652191, 0.0462062 , 0.20177573, 0.5688222 ],
       [0.58084278, 0.15260342, 0.0665476

In [23]:
#give you standarize list, mean=0 and varience =1
random_=np.random.randn(10)
random_

array([-0.249664  , -0.10248915,  1.38624919,  1.13216069,  0.53458762,
        2.68734453, -1.3699276 ,  1.10946877,  0.14978882, -0.36889207])

In [24]:
random_=np.random.randn(10,10)
random_


array([[ 0.87109563,  1.1565789 ,  0.33300299, -1.18742792, -0.30535612,
        -1.28263512, -1.15963543, -2.17837933,  0.24953348, -0.44840915],
       [ 0.42763778, -1.12745736, -0.31700395,  0.16964091, -0.5094929 ,
         0.65433552, -0.36992419,  0.87626766, -0.40563945,  0.96944211],
       [-0.1941959 , -0.67065882, -0.47950219, -1.31351873,  0.06753176,
        -0.59579741,  0.89794742,  1.21630262,  0.66732725, -1.37199611],
       [-1.1542176 , -0.93564404,  0.28013   , -0.35874918, -0.88658326,
         0.17569069,  0.40057419, -1.85633983, -0.45100294, -0.27860357],
       [-2.06294948, -1.20728453,  0.19123182,  0.48261966,  1.49202772,
         1.06543898,  1.31868501,  0.78068611, -0.51872356, -0.80087083],
       [ 0.28672568,  0.77407805, -1.01643547, -0.04804702, -0.23295984,
        -0.24336259, -0.9307097 , -0.15414956, -0.32019419, -0.30194003],
       [ 0.69061678,  0.83376083, -0.67128203, -0.45481954,  1.07671521,
        -1.36625182, -0.92233305,  1.25927386

In [25]:
# one item is giving max excluding
random__=np.random.randint(2)
random__

1

In [26]:
random__=np.random.randint(2,6)
random__

4

In [27]:
random__=np.random.randint(2,6,2)
random__

array([3, 3])

In [28]:
random___=np.random.randint(2,6,(2,4))
random___

array([[4, 5, 3, 2],
       [3, 5, 4, 3]])

In [29]:
# if we want to stop randomaztion use seed in same cell with any number
np.random.seed(2)
random__=np.random.randint(2,6,2)
random__

array([2, 5])

In [30]:
random__=np.random.randint(2,6,2)
random__

array([3, 2])

In [31]:
np.random.seed(2)
random__=np.random.randint(2,6,2)
random__

array([2, 5])

In [32]:
np.random.seed(3)
random__=np.random.randint(2,6,2)
random__

array([4, 2])

In [33]:
np.random.seed(3)
random__=np.random.randint(2,6,2)
random__

array([4, 2])

In [34]:
l=[1,2,3,4,5,6,7,7]
newarray=np.array(l)
newarray

array([1, 2, 3, 4, 5, 6, 7, 7])

In [36]:
newarray.reshape(2,4)

array([[1, 2, 3, 4],
       [5, 6, 7, 7]])

In [37]:
# 1 column and fit rows accordingly
reshaped=newarray.reshape(-1,1)
reshaped

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [7]])

In [38]:
reshaped=newarray.reshape(1,-1)
reshaped

array([[1, 2, 3, 4, 5, 6, 7, 7]])

In [39]:
#convert 2d to 1d
reshaped=newarray.reshape(-1)
reshaped

array([1, 2, 3, 4, 5, 6, 7, 7])

In [40]:
reshaped.argmin()

0

In [41]:
reshaped.argmax()

6

In [42]:
reshaped.max()

7

In [43]:
l=[1,2,3,4,5,6,7,7]
newarray=np.array(l)
newarray=newarray.reshape(2,4)
newarray

array([[1, 2, 3, 4],
       [5, 6, 7, 7]])

In [44]:
newarray.argmax()

6