In [1]:
import numpy as np

In [2]:
array=np.arange(0,10)
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
slice1=array[0:2]
slice1

array([0, 1])

In [4]:
slice1=array[:6]
slice1

array([0, 1, 2, 3, 4, 5])

In [5]:
slice1=100

In [6]:
slice1

100

In [7]:
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
a1=array[:4]
a2=array[4:]
print(a1,a2)

[0 1 2 3] [4 5 6 7 8 9]


In [9]:
slice2=array[:6]
slice2

array([0, 1, 2, 3, 4, 5])

In [10]:
slice2[:]=100

In [11]:
slice2

array([100, 100, 100, 100, 100, 100])

In [12]:
array

array([100, 100, 100, 100, 100, 100,   6,   7,   8,   9])

In [13]:
array2=np.arange(0,10)
array2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
slice2=array2[0:7]
slice3=slice2.copy()

In [15]:
slice3[:]=200

In [16]:
slice3

array([200, 200, 200, 200, 200, 200, 200])

In [17]:
array2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
two_d=np.array([[1,2,3],[4,5,6],[7,8,9]])
two_d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [19]:
two_d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [20]:
two_d[1:]

array([[4, 5, 6],
       [7, 8, 9]])

In [22]:
two_d[1][1]

5

In [23]:
two_d[1,1]


5

In [24]:
two_d[:,1]

array([2, 5, 8])

In [25]:
two_d[:2,:]

array([[1, 2, 3],
       [4, 5, 6]])

In [27]:
two_d[:2][:]

array([[1, 2, 3],
       [4, 5, 6]])