In [1]:
import numpy as np

In [3]:
arr=np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
new_arry=arr+5

In [5]:
new_arry

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [6]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [7]:
# both should have same shape, they do addition or items 
new_arry+new_arry

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30])

In [8]:
new_arry-new_arry

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [9]:
arr2=np.arange(0,11)
arr2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [11]:
# in numpy deivided by zero doesnt give error it just replace with nan
arr2/arr2

<ipython-input-11-3a28f8da6c6f>:2: RuntimeWarning: invalid value encountered in true_divide
  arr2/arr2


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [12]:
but in python it is an error
1/0

SyntaxError: invalid syntax (<ipython-input-12-1eaa50d9a0ff>, line 1)

In [14]:
# in this case it will change nan to infinty
newar3=1/arr2

<ipython-input-14-c1fe194f5dfc>:2: RuntimeWarning: divide by zero encountered in true_divide
  newar3=1/arr2


In [15]:
newar3

array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])

In [17]:
arr4=np.arange(0,11)
arr4

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [20]:
print("max =>{} , sum=>{}, variance=>{}, stand diav=>{}".format(arr4.max(),arr4.sum(),arr4.var(),arr4.std()))

max =>10 , sum=>55, variance=>10.0, stand diav=>3.1622776601683795


In [21]:
arr4=np.arange(0,25).reshape(5,5)
arr4

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [22]:
arr4.sum()

300

In [27]:
#we can define the axis here
# 1 means across the column not columns sum( from left to right)
arr4.sum(axis=1) 

array([ 10,  35,  60,  85, 110])

In [26]:
# 0 means across the rows not rows sum ( from top to down)
arr4.sum(axis=0)

array([50, 55, 60, 65, 70])